
version: "3.5"
services:
  jenkins:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /Users/${USER}/.jenkins/hh-jenkins-home
        target: /var/jenkins_home
    ports:
      - "9000:8080"
      - "50000:50000"
    image: hh-jenkins
    container_name: 'local.jenkins'