apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-hh-app
  template:
    metadata:
      labels:
        app: hello-hh-app
    spec:
      containers:
        - name: hello-hh-ctr
          image: dipeshy/hh-helloworld:0.0.1
          ports:
          - containerPort: 5001
  